Adding plist edit to remove encyption message in Testflight

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -84,7 +84,7 @@ jobs:
           projectPath: ${{ matrix.projectPath }}
           githubToken: ${{ secrets.GITHUB_TOKEN }}
           versioning: Custom
-          version: 1.1.0
+          version: 1.1
           androidVersionCode: ${{ github.run_number }}
           allowDirtyBuild: true
           buildsPath: dist
@@ -120,8 +120,8 @@ jobs:
           name: Build-iOS
       - name: Make build scripts executeable and change directory to the location of the xcode project
         run: chmod +x /Users/runner/work/BeamableProduct/BeamableProduct/iOS/process_symbols.sh && chmod +x /Users/runner/work/BeamableProduct/BeamableProduct/iOS/MapFileParser.sh && chmod +x /Users/runner/work/BeamableProduct/BeamableProduct/iOS/usymtool && cd iOS/
-      - name: what is the head ref?
-        run:  echo ${{ github.ref }}
+      - name: Edit the plist to automatically manage encryption notice in Testflight.
+        run:  /usr/libexec/PlistBuddy -c "Add :ITSAppUsesNonExemptEncryption bool false" /Users/runner/work/BeamableProduct/BeamableProduct/iOS/Info.plist || echo "Could not set encryption exception, this means it already exists"
       - uses: yukiarrr/ios-build-action@v1.4.0
         if: ${{ github.ref == 'refs/heads/iOS' }}
         with:
